"""tabelas iniciais

Revision ID: 2b141f7b3553
Revises: 
Create Date: 2025-09-07 20:34:55.714794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b141f7b3553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apartamentos',
    sa.Column('Numero_AP', sa.String(length=20), nullable=False),
    sa.Column('Ocupado', sa.Boolean(), nullable=True),
    sa.Column('Alugado', sa.Boolean(), nullable=True),
    sa.Column('Venda', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Numero_AP')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Apartamentos')
    # ### end Alembic commands ###
