"""tabelas iniciais

Revision ID: 4026c80b8392
Revises: 2b141f7b3553
Create Date: 2025-09-07 20:36:12.720234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4026c80b8392'
down_revision = '2b141f7b3553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
