"""create tables

Revision ID: 767e593f0c9d
Revises: 4026c80b8392
Create Date: 2025-09-29 02:29:03.616032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767e593f0c9d'
down_revision = '4026c80b8392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Moradores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('morador_apartamento',
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('apartamento_numero', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['apartamento_numero'], ['Apartamentos.Numero_AP'], ),
    sa.ForeignKeyConstraint(['morador_id'], ['Moradores.id'], ),
    sa.PrimaryKeyConstraint('morador_id', 'apartamento_numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morador_apartamento')
    op.drop_table('Moradores')
    # ### end Alembic commands ###
