"""create contas table

Revision ID: b05acb9b041a
Revises: 767e593f0c9d
Create Date: 2025-10-12 23:11:33.817725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05acb9b041a'
down_revision = '767e593f0c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('pendente', sa.Boolean(), nullable=True),
    sa.Column('morador_id', sa.Integer(), nullable=False),
    sa.Column('numero_AP', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['morador_id'], ['Moradores.id'], ),
    sa.ForeignKeyConstraint(['numero_AP'], ['Apartamentos.Numero_AP'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas')
    # ### end Alembic commands ###
